Level 2
FreddyMutant/movies-explorer-frontend pull request #1
Opened 2023-10-05 15:35 UTC by FreddyMutant

2023-10-05 16:51 UTC, FreddyMutant commented
Макет dark-3
Приложение доступно по адресу https://freddymutant.nomoredomainsicu.ru
Чтобы изменить на залогиненное состояние достаточно ввести валидные данные в форме Войти signin

2023-10-05 17:54 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- Сохраненные фильмы - https://yadi.sk/d/hBIQnHr8zwtdtw https://yadi.sk/d/D-qgpLt903b8Gg https://yadi.sk/i/dN8IIT8nl2HedQ отступ до подвала отличается

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [ ] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

	- Ссылка Регистрация на странице Входа нуждается в актуализации

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/C6FLQCjHiyz4cQ в проекте есть ошибки БЭМ, воспользуйтесь валидатором для проверки https://nglazov.github.io/bem-validator-page/
	- project__about-1, project__time-1, student__info-1 - в именование классов не используйте цифры, хорошо давать логические смысловые названия для классов.
	- project__time-week_front, project__time-week_back - в именовании не опирайтесь на внутренний контент, так блок может повторно быть использован или контент внутри изменится, название класса будет путать. Здесь хорошо помогут сложные модификаторы БЭМ, например, project__time-week_theme_main

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/azCCCEFfMRZ9bg опишите изображению пропорции и позицию, чтобы не растягивалось

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Вход/Рег/Профиль/404)
	- project__time - в данном блоке тектовой контент оформлен дивами
	- anchors - для навигационных тегов хорошо использовать селектор nav
	- profile-landing.svg, profile-main.svg сохраните только векторную часть, контент следует описывать в разметке

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- https://yadi.sk/d/w5Gbk8Fm8aMHJQ https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [ ] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,

		- Из папки компонентов хорошо бы вытянуть другие компоненты (Main, Movies, ...). Они как части пазлов, могут собирать и другие страницы.

	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Для тегов <form> так же следует заполнить атрибут name

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 52

2023-10-05 20:29 UTC, FreddyMutant commented
>Сохраненные фильмы - https://yadi.sk/d/hBIQnHr8zwtdtw https://yadi.sk/d/D-qgpLt903b8Gg https://yadi.sk/i/dN8IIT8nl2HedQ отступ до подвала отличается - добавлено дополнительное место. Не совсем понятно зачем оставлять лишнее пространство в saved-movies?!

>Ссылка Регистрация на странице Входа нуждается в актуализации - решено

>https://yadi.sk/d/C6FLQCjHiyz4cQ в проекте есть ошибки БЭМ, воспользуйтесь валидатором для проверки - решено
>project__about-1, project__time-1, student__info-1 - решено
>project__time-week_front, project__time-week_back - решено
>profile-landing.svg, profile-main.svg сохраните только векторную часть, контент следует описывать в разметке - решено

>https://yadi.sk/d/azCCCEFfMRZ9bg опишите изображению пропорции и позицию, чтобы не растягивалось - решено

>Каждый основной контент на странице следует обернуть main, все кроме header и footer (Вход/Рег/Профиль/404) - решено
>project__time - в данном блоке тектовой контент оформлен дивами - решено
>anchors - для навигационных тегов хорошо использовать селектор nav - решено
>profile-landing.svg, profile-main.svg сохраните только векторную часть, контент следует описывать в разметке - решено


>Работа модальных окон настроена.
> Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется - решено
> также нижняя панель с кнопками меняет свой вид. - Кнопка "сохранить" меняет свой вид взависиомти от валидности данных
> Также есть состояния ошибки (это можно заложить в верстку). - Временное состояние ошибки можно сэмулировать нажатием кнопки сохранить.

> Разметка портирована в JSX - непонятно что именно не так в этом блоке проверок, приведите, пожалуйста, пример.

>Из папки компонентов хорошо бы вытянуть другие компоненты (Main, Movies, ...). Они как части пазлов, могут собирать и другие страницы. - решено

>Для тегов так же следует заполнить атрибут name - если речь про "input className="search__input"" то ему добавлен name

2023-10-06 06:12 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
Отличная работа по предыдущему ревью, поздравляю Ваш проект принимается. Желаю Вам успехов во всех начинаниях!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 100

		- https://yadi.sk/d/gpE8Uy49A2dc4g Из папки компонентов хорошо бы вытянуть другие компоненты (Main, Movies, ...). Они как части пазлов, могут собирать и другие страницы.
		- В прошлом ревью тег формы съелся редактором - Для тегов `<form>` так же следует заполнить атрибут name

2023-10-06 06:21 UTC, merged